### ISSUE TITLE
react表单验证有没合适的方法去做？

### ISSUE THREAD

**Issue by lulei90** [GuoYongfeng/react-fundamental#1]
郭老师 你好 想了解下 react在做表单验证这块 要怎么去处理  有没合适的插件去弄？

**Comment by GuoYongfeng** [comment]
可以封装表单校验组件，比如：[react-validation](https://github.com/Lesha-spr/react-validation)、[ant.design/components/form-cn](https://ant.design/components/form-cn/#components-form-demo-dynamic-rule)
